title: SUDS Conference 2024
email: sudsconf@jpl.nasa.gov
description: >- 
  The 1st Annual Science Understanding through Data Science (SUDS) Conference
  and Workshop.
url: "https://sudsconf.com"
github_username: jplmlia