title: SUDS Conference 2024
email: jake.h.lee@jpl.nasa.gov
description: >- 
  The 1st Annual Science Understanding through Data Science (SUDS) Conference
  and Workshop.
baseurl: ""
url: "https://sudsconf.com"
twitter_username: 
github_username: jplmlia